---
title: "wordcloud"
date: '2025-10-20'
output: html_document
---

```{r}
library(quanteda)
library(reticulate)
library(readxl)
library(tidyverse)
library(gutenbergr)
library(tidytext)
library(stm)
library(tidyr)
library(rjson)
#library(preText)
library(topicmodels)
library(tm)
library(reshape2)
library(ggplot2)
library(wordcloud)
library(pals)
library(RColorBrewer)



### Please change the working directory to the root directory 
## setwd("/Users/lihan/Documents/work/Research/media/EJ replication/Media Replication Package/3-replication-package")
 

# Set root path;  the replicators need to reset the root directory 

root <- "/Users/lihan/Documents/work/Research/media/EJ Replication/Media Replication Package/3-replication-package"

data_path <- file.path(root, "data/source data")

full_path <- file.path(data_path, "LDA_tmres1_chr.csv")

beta1 <- read.csv(file = full_path)

beta <- t(beta1)
```






```{r}
out_path <- file.path(root, "OUTPUT/appendix/wordcloud/")

# Reorder the topics to be consistent with those in the paper.
my_vector <- c(5, 1, 10, 4, 8, 11, 6, 3, 9, 2, 12, 7)

for (i in 1:12) {
  column_name <- paste('V', as.character(i), sep = '')
  df <- data.frame(term = rownames(beta), p = beta[, i])
  row.names(df) <- seq(1, 53926, 1)
  df1 <- df
  j <- my_vector[i]
  
  # Create a unique filename for each word cloud
  pdf_filename <- paste(out_path, "topic_", j, ".pdf", sep = "")

  # Open a PDF device with the unique filename
  pdf(file = pdf_filename, width = 8, height = 6)  # Adjust width and height as needed

  wordcloud(words = df1$term,
            freq = df1$p,
            max.words = 60,
            random.order = FALSE,
            rot.per = 0.35,
            colors = brewer.pal(8, "Dark2"))

  # Close the PDF device to save the current word cloud as a PDF file
  dev.off()
}
```



